baseURL = "https://mahti.org"
languageCode = "fi-fi"
title = "mahti.org"

[taxonomies]
  muistiinpano = "muistiinpanoja"
  blogi = "blogit"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "paraiso-light"
    tabWidth = 2
